// Runtime-safe Supabase client.
//
// We do NOT edit the autogenerated client.ts; instead we provide a stable client that
// works even if Vite env vars are missing in some preview/build contexts.

import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { getSupabasePublicConfig } from "@/lib/publicConfig";

const { url: SUPABASE_URL, publishableKey: SUPABASE_PUBLISHABLE_KEY } = getSupabasePublicConfig();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
